from AoE2ScenarioParser.datasets.object_support import *
from AoE2ScenarioParser.datasets.units import *

# list of all trainable units; must match xx.hpp
unitsList = [
    UnitInfo.ARCHER,
    UnitInfo.SKIRMISHER,
    UnitInfo.SLINGER,
    UnitInfo.CAVALRY_ARCHER,
    UnitInfo.ELEPHANT_ARCHER,
    UnitInfo.GENITOUR,
    # UnitInfo.GRENADIER,
    # UnitInfo.XIANBEI_RAIDER,
    UnitInfo.HAND_CANNONEER,
    UnitInfo.MILITIA,
    UnitInfo.SPEARMAN,
    UnitInfo.EAGLE_SCOUT,
    UnitInfo.FLEMISH_MILITIA,
    # UnitInfo.FIRE_LANCER,
    # UnitInfo.JIAN_SWORDSMAN,
    UnitInfo.CONDOTTIERO,
    UnitInfo.SCOUT_CAVALRY,
    UnitInfo.SHRIVAMSHA_RIDER,
    UnitInfo.KNIGHT,
    UnitInfo.STEPPE_LANCER,
    UnitInfo.CAMEL_SCOUT,
    UnitInfo.BATTLE_ELEPHANT,
    # UnitInfo.HEI_GUANG_CAVALRY,
    UnitInfo.XOLOTL_WARRIOR,
    UnitInfo.BATTERING_RAM,
    UnitInfo.ARMORED_ELEPHANT,
    UnitInfo.MANGONEL,
    # UnitInfo.ROCKET_CART,
    UnitInfo.SCORPION,
    UnitInfo.SIEGE_TOWER,
    # UnitInfo.WAR_CHARIOT_FOCUS,
    UnitInfo.BOMBARD_CANNON,
    # UnitInfo.MOUNTED_TREBUCHET,
    # UnitInfo.TRACTION_TREBUCHET,
    UnitInfo.FLAMING_CAMEL,
    UnitInfo.FISHING_SHIP,
    UnitInfo.TRANSPORT_SHIP,
    UnitInfo.FIRE_GALLEY,
    UnitInfo.TRADE_COG,
    UnitInfo.DEMOLITION_RAFT,
    UnitInfo.GALLEY,
    UnitInfo.TURTLE_SHIP,
    UnitInfo.LONGBOAT,
    UnitInfo.CARAVEL,
    UnitInfo.DROMON,
    # UnitInfo.LOU_CHUAN,
    UnitInfo.THIRISADAI,
    UnitInfo.CANNON_GALLEON,
    UnitInfo.MONK,
    UnitInfo.MISSIONARY,
    UnitInfo.WARRIOR_PRIEST,
    UnitInfo.PETARD,
    UnitInfo.TREBUCHET_PACKED,
    UnitInfo.COMPOSITE_BOWMAN,
    UnitInfo.JAGUAR_WARRIOR,
    UnitInfo.RATHA_MELEE,
    UnitInfo.RATHA_RANGED,
    UnitInfo.CAMEL_ARCHER,
    UnitInfo.HUSSITE_WAGON,
    UnitInfo.LONGBOWMAN,
    UnitInfo.KONNIK,
    UnitInfo.KONNIK_DISMOUNTED,
    UnitInfo.COUSTILLIER,
    UnitInfo.ARAMBAI,
    UnitInfo.CATAPHRACT,
    UnitInfo.WOAD_RAIDER,
    UnitInfo.CHU_KO_NU,
    UnitInfo.KIPCHAK,
    UnitInfo.URUMI_SWORDSMAN,
    UnitInfo.SHOTEL_WARRIOR,
    UnitInfo.THROWING_AXEMAN,
    UnitInfo.MONASPA,
    UnitInfo.HUSKARL,
    UnitInfo.CHAKRAM_THROWER,
    UnitInfo.GHULAM,
    UnitInfo.TARKAN,
    UnitInfo.KAMAYUK,
    UnitInfo.GENOESE_CROSSBOWMAN,
    UnitInfo.SAMURAI,
    # UnitInfo.IRON_PAGODA,
    # UnitInfo.LIAO_DAO,
    UnitInfo.BALLISTA_ELEPHANT,
    UnitInfo.WAR_WAGON,
    UnitInfo.LEITIS,
    UnitInfo.MAGYAR_HUSZAR,
    UnitInfo.KARAMBIT_WARRIOR,
    UnitInfo.GBETO,
    UnitInfo.PLUMED_ARCHER,
    UnitInfo.MANGUDAI,
    UnitInfo.WAR_ELEPHANT,
    UnitInfo.OBUCH,
    UnitInfo.ORGAN_GUN,
    UnitInfo.CENTURION,
    UnitInfo.MAMELUKE,
    # UnitInfo.WHITE_FEATHER_GUARD,
    UnitInfo.SERJEANT,
    UnitInfo.BOYAR,
    UnitInfo.CONQUISTADOR,
    UnitInfo.KESHIK,
    UnitInfo.TEUTONIC_KNIGHT,
    UnitInfo.JANISSARY,
    UnitInfo.RATTAN_ARCHER,
    UnitInfo.BERSERK,
    # UnitInfo.TIGER_CAVALRY,
    # UnitInfo.FIRE_ARCHER,
]
